### Preparing the data in HDF5 Formatting
Switching the .fits file to an HDF5 for better storage management and mainly practice

Importing the appropriate packages.

In [1]:
from astropy.table import Table
from astropy.io import fits
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
import h5py
from sklearn.preprocessing import MinMaxScaler

In [2]:
# data = Table.read('/arc/home/aydanmckay/gaiahike/bp_rp_apogee.fits').to_pandas()
data = Table.read('/arc/home/aydanmckay/bp_rp_apogee_filtered.fits').to_pandas()

In [3]:
data.shape

(443406, 236)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 342402 entries, 0 to 443405
Columns: 236 entries, dr3_source_id to gaiaedr3_phot_g_mean_mag
dtypes: float32(10), float64(223), int64(1), object(2)
memory usage: 606.1+ MB


In [5]:
with pd.option_context('mode.use_inf_as_na', True):
    data.dropna(inplace=True)
data.shape

(342402, 236)

needs to be 342402 ^^

In [6]:
labels = ["bp_1", "bp_2", "bp_3", "bp_4", "bp_5", "bp_6", "bp_7",
          "bp_8", "bp_9", "bp_10", "bp_11", "bp_12", "bp_13", "bp_14",
          "bp_15", "bp_16", "bp_17", "bp_18", "bp_19", "bp_20", "bp_21",
          "bp_22", "bp_23", "bp_24", "bp_25", "bp_26", "bp_27", "bp_28",
          "bp_29", "bp_30", "bp_31", "bp_32", "bp_33", "bp_34", "bp_35",
          "bp_36", "bp_37", "bp_38", "bp_39", "bp_40", "bp_41", "bp_42",
          "bp_43", "bp_44", "bp_45", "bp_46", "bp_47", "bp_48", "bp_49",
          "bp_50", "bp_51", "bp_52", "bp_53", "bp_54", "bp_55", "rp_1",
          "rp_2", "rp_3", "rp_4", "rp_5", "rp_6", "rp_7", "rp_8",
          "rp_9", "rp_10", "rp_11", "rp_12", "rp_13", "rp_14", "rp_15",
          "rp_16", "rp_17", "rp_18", "rp_19", "rp_20", "rp_21", "rp_22",
          "rp_23", "rp_24", "rp_25", "rp_26", "rp_27", "rp_28", "rp_29",
          "rp_30", "rp_31", "rp_32", "rp_33", "rp_34", "rp_35", "rp_36",
          "rp_37", "rp_38", "rp_39", "rp_40", "rp_41", "rp_42", "rp_43",
          "rp_44", "rp_45", "rp_46", "rp_47", "rp_48", "rp_49", "rp_50",
          "rp_51", "rp_52", "rp_53", "rp_54", "rp_55"]
elabels = ["bpe_1", "bpe_2", "bpe_3", "bpe_4", "bpe_5", "bpe_6", "bpe_7",
          "bpe_8", "bpe_9", "bpe_10", "bpe_11", "bpe_12", "bpe_13", "bpe_14",
          "bpe_15", "bpe_16", "bpe_17", "bpe_18", "bpe_19", "bpe_20", "bpe_21",
          "bpe_22", "bpe_23", "bpe_24", "bpe_25", "bpe_26", "bpe_27", "bpe_28",
          "bpe_29", "bpe_30", "bpe_31", "bpe_32", "bpe_33", "bpe_34", "bpe_35",
          "bpe_36", "bpe_37", "bpe_38", "bpe_39", "bpe_40", "bpe_41", "bpe_42",
          "bpe_43", "bpe_44", "bpe_45", "bpe_46", "bpe_47", "bpe_48", "bpe_49",
          "bpe_50", "bpe_51", "bpe_52", "bpe_53", "bpe_54", "bpe_55", "rpe_1",
          "rpe_2", "rpe_3", "rpe_4", "rpe_5", "rpe_6", "rpe_7", "rpe_8",
          "rpe_9", "rpe_10", "rpe_11", "rpe_12", "rpe_13", "rpe_14", "rpe_15",
          "rpe_16", "rpe_17", "rpe_18", "rpe_19", "rpe_20", "rpe_21", "rpe_22",
          "rpe_23", "rpe_24", "rpe_25", "rpe_26", "rpe_27", "rpe_28", "rpe_29",
          "rpe_30", "rpe_31", "rpe_32", "rpe_33", "rpe_34", "rpe_35", "rpe_36",
          "rpe_37", "rpe_38", "rpe_39", "rpe_40", "rpe_41", "rpe_42", "rpe_43",
          "rpe_44", "rpe_45", "rpe_46", "rpe_47", "rpe_48", "rpe_49", "rpe_50",
          "rpe_51", "rpe_52", "rpe_53", "rpe_54", "rpe_55"]

In [7]:
# for label in elabels:
#     data = data[(data[label] < 10) & (data[label] > -10)]
# data.shape

In [8]:
# for small datasets
# data = data.sample(n=50000,random_state=42)

In [9]:
data.shape

(342402, 236)

In [10]:
# feh = data['fe_h']
feh = data['feh']
teff = data['teff']
# am = data['alpha_m']
am = data['alpha_fe']
logg = data['logg']
gmag = data['gaiaedr3_phot_g_mean_mag']
normalize = lambda x, n: x / (10 ** (8.5 - n / 2.5))
xp = []
xpe = []
for elabel,label,g in zip(elabels,labels,gmag):
    xp.append(data[label])
    xpe.append(data[elabel])
xp = np.array(xp)
xpe = np.array(xpe)

In [11]:
xp.T.shape

(342402, 110)

In [12]:
gmag_train, gmag_test, feh_train, feh_test, teff_train, teff_test, am_train, am_test, logg_train, logg_test, xp_train, xp_test, xpe_train, xpe_test = train_test_split(
    gmag,
    feh,
    teff,
    am,
    logg,
    xp.T,
    xpe.T,
    test_size=0.1,
    random_state=42
)

In [13]:
gmag_train, gmag_valid, feh_train, feh_valid, teff_train, teff_valid, am_train, am_valid, logg_train, logg_valid, xp_train, xp_valid, xpe_train, xpe_valid = train_test_split(
    gmag_train,
    feh_train,
    teff_train,
    am_train,
    logg_train,
    xp_train,
    xpe_train,
    test_size=0.1,
    random_state=42
)

In [14]:
xp_train.shape

(277344, 110)

In [15]:
# Create a HDF5 file
hierarchicalFileName  = "/arc/home/aydanmckay/filtered_apogee_bprp_gmag.h5"
with h5py.File(hierarchicalFileName, 'w') as hierarchicalFile:
    # Create a group under root
    
    train = hierarchicalFile.create_group("group_1")
    valid = hierarchicalFile.create_group("group_2")
    test = hierarchicalFile.create_group("group_3")
    
    train['data'] = np.array(
        [feh_train,
         logg_train,
         teff_train,
         am_train
        ]
    )
    valid['data'] = np.array(
        [feh_valid,
         logg_valid,
         teff_valid,
         am_valid
        ]
    )
    test['data'] = np.array(
        [feh_test,
         logg_test,
         teff_test,
         am_test
        ]
    )
    train['label'] = xp_train.T
    train['e_label'] = xpe_train.T
    valid['label'] = xp_valid.T
    valid['e_label'] = xpe_valid.T
    test['label'] = xp_test.T
    test['e_label'] = xpe_test.T
    
    train['gmag'] = gmag_train
    valid['gmag'] = gmag_valid
    test['gmag'] = gmag_test

    print(hierarchicalFile["/"])
    print(train)
    print(valid)
    print(train['data'])
    print(valid["label"])
    print(test['e_label'])
    print(train['gmag'])

<HDF5 group "/" (3 members)>
<HDF5 group "/group_1" (4 members)>
<HDF5 group "/group_2" (4 members)>
<HDF5 dataset "data": shape (4, 277344), type "<f4">
<HDF5 dataset "label": shape (110, 30817), type "<f8">
<HDF5 dataset "e_label": shape (110, 34241), type "<f8">
<HDF5 dataset "gmag": shape (277344,), type "<f8">


In [1]:
scalerlist = [MinMaxScaler() for _ in range(110)]
with h5py.File("/arc/home/aydanmckay/filtered_apogee_bprp_gmag.h5", 'r') as f:
    d = f['group_1']['label']
    dn = f['group_1']['gmag']
    dnset = dn[:]
    dset = d[:]
    ydat = np.array([
        scaler.fit_transform(d[[it]].T).flatten() for it,scaler in enumerate(scalerlist)
    ])
    print(ydat.shape[1])
    print(f['group_1']['label'].shape[1])
    print(f['group_1']['data'].T.shape)

NameError: name 'MinMaxScaler' is not defined

In [17]:
dnset

array([11.97159958, 11.47179985, 12.67520046, ..., 14.96010017,
       15.31709957, 12.98519993])

In [18]:
dset.shape

(110, 277344)

In [19]:
dset

array([[ 2.02609231e+04,  2.69782349e+04,  9.86446161e+03, ...,
         7.13351425e+02,  3.89955423e+02,  7.57215395e+03],
       [-3.65745808e+03,  7.91457178e+02, -4.22764807e+02, ...,
         1.70263116e+02,  7.25752556e+01, -7.15883206e+02],
       [ 1.32147719e+02, -1.33373084e+03, -4.08674320e+02, ...,
        -2.53846923e+01,  3.26919076e+00, -1.82072189e+02],
       ...,
       [-2.44042793e-01, -2.59422665e-01, -2.75467906e-01, ...,
         1.94004979e-01, -1.72063488e-01,  3.15333724e-01],
       [ 5.17330957e-01,  4.15424507e-01,  4.90012641e-02, ...,
         6.51290154e-02,  3.22979936e-02,  5.82865063e-02],
       [ 1.63693117e-01,  1.06058644e-01,  8.65011167e-02, ...,
         6.83874160e-02, -4.01585216e-02,  1.84792293e-01]])

In [20]:
ydat

array([[5.66649602e-03, 7.54559994e-03, 2.75818503e-03, ...,
        1.98249206e-04, 1.07782258e-04, 2.11693382e-03],
       [9.61146515e-01, 9.64305799e-01, 9.63443550e-01, ...,
        9.63864673e-01, 9.63795303e-01, 9.63235399e-01],
       [1.42388271e-01, 1.37683569e-01, 1.40652516e-01, ...,
        1.41882674e-01, 1.41974638e-01, 1.41379790e-01],
       ...,
       [2.58098531e-01, 2.58089488e-01, 2.58080054e-01, ...,
        2.58356089e-01, 2.58140852e-01, 2.58427426e-01],
       [1.96157082e-01, 1.96030872e-01, 1.95577059e-01, ...,
        1.95597033e-01, 1.95556372e-01, 1.95588559e-01],
       [4.31941235e-01, 4.31820620e-01, 4.31779690e-01, ...,
        4.31741783e-01, 4.31514621e-01, 4.31985391e-01]])

In [21]:
dset.T.shape

(277344, 110)